# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Chris Thomas
email: cthomas@onhaven.net
description: >- # this means to ignore newlines until "baseurl:"
  Christopher Thomas is a computer scientist with an interest in web applications and systems administration.
  This website serves as a portfolio, blog and résumé.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: Faore
github_username:  Faore
author:
  name: John Doe
# Build settings
markdown: kramdown
remote_theme: "mmistakes/jekyll-theme-basically-basic"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

sass:
    sass_dir: ./_sass

paginate: 5
paginate_path: "/blog/page:num/"
permalink: /blog/:categories/:year/:month/:day/:title/

search: true
search_provider: algolia
algolia:
  application_id: 87A5QSDT7S
  index_name: faore.github.io
  search_only_api_key: 9b959fced1eb45e60589bb8dd0ede77f
  powered_by: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
exclude:
  - .idea